<a href="https://colab.research.google.com/github/finardi/tutos/blob/master/Pandas_Explode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
pd.option_context("display.max_rows", 999, "display.max_columns", 999, 'max_colwidth', -1)
pd.set_option('max_colwidth', 400)

In [ ]:
pd.__version__

'1.0.5'

In [ ]:
a  = ['isso é uma lista', 'que possui o objetivo', 'de entender', 'como funciona o explode' ]
b  = ['essa é uma outra lista', 'porém', 'essa lista', 'não irá utilizar o', 'pandas explode' ]
c  = ['humm', 'então temos 3 listas', 'essa daqui', 'só', 'vai tentar', 'ver', 'se tudo', 'funciona', 'corretamente' ]

df = pd.DataFrame(
    {
        'Text_A':[a, b, c],
        'Func':[981, 281,271], 
        'Text_B':[['texto', 'palavra', 'char'], ['char', 'index', 'var'], ['text with word', 'word with char']],
     }
      )


df

                                                                                           Text_A  ...                            Text_B
0                 [isso é uma lista, que possui o objetivo, de entender, como funciona o explode]  ...            [texto, palavra, char]
1                 [essa é uma outra lista, porém, essa lista, não irá utilizar o, pandas explode]  ...                [char, index, var]
2  [humm, então temos 3 listas, essa daqui, só, vai tentar, ver, se tudo, funciona, corretamente]  ...  [text with word, word with char]

[3 rows x 3 columns]

# Pandas explode em Text_A

In [ ]:
df_explode_Text_A = df.explode('Text_A', ); df_explode_Text_A.reset_index(drop=True)

                     Text_A  Func                            Text_B
0          isso é uma lista   981            [texto, palavra, char]
1     que possui o objetivo   981            [texto, palavra, char]
2               de entender   981            [texto, palavra, char]
3   como funciona o explode   981            [texto, palavra, char]
4    essa é uma outra lista   281                [char, index, var]
5                     porém   281                [char, index, var]
6                essa lista   281                [char, index, var]
7        não irá utilizar o   281                [char, index, var]
8            pandas explode   281                [char, index, var]
9                      humm   271  [text with word, word with char]
10     então temos 3 listas   271  [text with word, word with char]
11               essa daqui   271  [text with word, word with char]
12                       só   271  [text with word, word with char]
13               vai tentar   271  [text with word, word with char]
14                      ver   271  [text with word, word with char]
15                  se tudo   271  [text with word, word with char]
16                 funciona   271  [text with word, word with char]
17             corretamente   271  [text with word, word with char]

In [ ]:
# depois em Text_B
df_explode_Text_A.explode('Text_B').reset_index(drop=True)

                     Text_A  Func          Text_B
0          isso é uma lista   981           texto
1          isso é uma lista   981         palavra
2          isso é uma lista   981            char
3     que possui o objetivo   981           texto
4     que possui o objetivo   981         palavra
5     que possui o objetivo   981            char
6               de entender   981           texto
7               de entender   981         palavra
8               de entender   981            char
9   como funciona o explode   981           texto
10  como funciona o explode   981         palavra
11  como funciona o explode   981            char
12   essa é uma outra lista   281            char
13   essa é uma outra lista   281           index
14   essa é uma outra lista   281             var
15                    porém   281            char
16                    porém   281           index
17                    porém   281             var
18               essa lista   281            char
19               essa lista   281           index
20               essa lista   281             var
21       não irá utilizar o   281            char
22       não irá utilizar o   281           index
23       não irá utilizar o   281             var
24           pandas explode   281            char
25           pandas explode   281           index
26           pandas explode   281             var
27                     humm   271  text with word
28                     humm   271  word with char
29     então temos 3 listas   271  text with word
30     então temos 3 listas   271  word with char
31               essa daqui   271  text with word
32               essa daqui   271  word with char
33                       só   271  text with word
34                       só   271  word with char
35               vai tentar   271  text with word
36               vai tentar   271  word with char
37                      ver   271  text with word
38                      ver   271  word with char
39                  se tudo   271  text with word
40                  se tudo   271  word with char
41                 funciona   271  text with word
42                 funciona   271  word with char
43             corretamente   271  text with word
44             corretamente   271  word with char

# Solução sem explode

In [ ]:
# 1o passo: concatenar todos os valores da coluna em um array
np.concatenate(df.Text_A.values)

array(['isso é uma lista', 'que possui o objetivo', 'de entender',
       'como funciona o explode', 'essa é uma outra lista', 'porém',
       'essa lista', 'não irá utilizar o', 'pandas explode', 'humm',
       'então temos 3 listas', 'essa daqui', 'só', 'vai tentar', 'ver',
       'se tudo', 'funciona', 'corretamente'], dtype='<U23')

In [ ]:
# 2o passo: o index é o str.len() de cada linha com numpy repeat
df.index.repeat(df.Text_A.str.len())

Int64Index([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype='int64')

In [ ]:
#3o passo: criar um dataset que recebe as colunas do 1o passo e o index do 2o passo.
s=pd.DataFrame({'Text_A':np.concatenate(df.Text_A.values)},index=df.index.repeat(df.Text_A.str.len()))
s

                    Text_A
0         isso é uma lista
0    que possui o objetivo
0              de entender
0  como funciona o explode
1   essa é uma outra lista
1                    porém
1               essa lista
1       não irá utilizar o
1           pandas explode
2                     humm
2     então temos 3 listas
2               essa daqui
2                       só
2               vai tentar
2                      ver
2                  se tudo
2                 funciona
2             corretamente

In [ ]:
# 4o passo: fazer join com as outras colunas
s.join(df.drop('Text_A', axis=1), how='left')

                    Text_A  Func                            Text_B
0         isso é uma lista   981            [texto, palavra, char]
0    que possui o objetivo   981            [texto, palavra, char]
0              de entender   981            [texto, palavra, char]
0  como funciona o explode   981            [texto, palavra, char]
1   essa é uma outra lista   281                [char, index, var]
1                    porém   281                [char, index, var]
1               essa lista   281                [char, index, var]
1       não irá utilizar o   281                [char, index, var]
1           pandas explode   281                [char, index, var]
2                     humm   271  [text with word, word with char]
2     então temos 3 listas   271  [text with word, word with char]
2               essa daqui   271  [text with word, word with char]
2                       só   271  [text with word, word with char]
2               vai tentar   271  [text with word, word with char]
2                      ver   271  [text with word, word with char]
2                  se tudo   271  [text with word, word with char]
2                 funciona   271  [text with word, word with char]
2             corretamente   271  [text with word, word with char]

In [ ]:
s=pd.DataFrame({'Text_A':np.concatenate(df.Text_A.values)},index=df.index.repeat(df.Text_A.str.len()))
s = s.join(df.drop('Text_A',1),how='left').reset_index(drop=True); s

                     Text_A  Func                            Text_B
0          isso é uma lista   981            [texto, palavra, char]
1     que possui o objetivo   981            [texto, palavra, char]
2               de entender   981            [texto, palavra, char]
3   como funciona o explode   981            [texto, palavra, char]
4    essa é uma outra lista   281                [char, index, var]
5                     porém   281                [char, index, var]
6                essa lista   281                [char, index, var]
7        não irá utilizar o   281                [char, index, var]
8            pandas explode   281                [char, index, var]
9                      humm   271  [text with word, word with char]
10     então temos 3 listas   271  [text with word, word with char]
11               essa daqui   271  [text with word, word with char]
12                       só   271  [text with word, word with char]
13               vai tentar   271  [text with word, word with char]
14                      ver   271  [text with word, word with char]
15                  se tudo   271  [text with word, word with char]
16                 funciona   271  [text with word, word with char]
17             corretamente   271  [text with word, word with char]

## Repetir o processo para a coluna Text_B

In [ ]:
s_B = pd.DataFrame({'Text_B':np.concatenate(s.Text_B.values)},index=s.index.repeat(s.Text_B.str.len())); s_B
s_B = s_B.join(s.drop('Text_B',axis=1),how='left').reset_index(drop=True); s_B

            Text_B                   Text_A  Func
0            texto         isso é uma lista   981
1          palavra         isso é uma lista   981
2             char         isso é uma lista   981
3            texto    que possui o objetivo   981
4          palavra    que possui o objetivo   981
5             char    que possui o objetivo   981
6            texto              de entender   981
7          palavra              de entender   981
8             char              de entender   981
9            texto  como funciona o explode   981
10         palavra  como funciona o explode   981
11            char  como funciona o explode   981
12            char   essa é uma outra lista   281
13           index   essa é uma outra lista   281
14             var   essa é uma outra lista   281
15            char                    porém   281
16           index                    porém   281
17             var                    porém   281
18            char               essa lista   281
19           index               essa lista   281
20             var               essa lista   281
21            char       não irá utilizar o   281
22           index       não irá utilizar o   281
23             var       não irá utilizar o   281
24            char           pandas explode   281
25           index           pandas explode   281
26             var           pandas explode   281
27  text with word                     humm   271
28  word with char                     humm   271
29  text with word     então temos 3 listas   271
30  word with char     então temos 3 listas   271
31  text with word               essa daqui   271
32  word with char               essa daqui   271
33  text with word                       só   271
34  word with char                       só   271
35  text with word               vai tentar   271
36  word with char               vai tentar   271
37  text with word                      ver   271
38  word with char                      ver   271
39  text with word                  se tudo   271
40  word with char                  se tudo   271
41  text with word                 funciona   271
42  word with char                 funciona   271
43  text with word             corretamente   271
44  word with char             corretamente   271